### ISSUE TITLE
Create an annotated tag version

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/EmonLibCM#5]
Hi @TrystanLea, can you create an annotated Tag version & release. It should then be possible to give a directive to use a specific version in PlatformIO I think.

so
```
lib_deps_external =
  https://github.com/openenergymonitor/EmonLibCM.git#master
```

```
lib_deps_external =
  https://github.com/openenergymonitor/EmonLibCM.git#v2.2.0
```

**Comment by glynhudson** [comment]
The usual way is to set the version number in `library.json`

https://github.com/openenergymonitor/EmonLibCM/blob/master/library.json#L5

PlatformIO will then automatically detect the new version, you can then specify in the usual way:

e.g
```
lib_deps_external =
  EmonLibCM @2.3.0
```

**Comment by borpin** [comment]
But you still need the git line so it gets pulled transparently. How do you combine the 2?

**Comment by glynhudson** [comment]
Platformio uses library.json to get the library version number. I've now specified library version 2.3.0 in EmonTxV3CM platformio.ini:

https://github.com/openenergymonitor/EmonTxV3CM/blob/master/platformio.ini#L11

**Comment by borpin** [comment]
That doesn't help being able to pull a specific version from GitHub.
